# Generated by Django 2.2.5 on 2021-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(max_length=15)),
                ('user_pw', models.CharField(max_length=15)),
                ('user_phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('c_date', models.DateTimeField()),
            ],
        ),
    ]
