# Generated by Django 3.2.5 on 2021-07-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(max_length=15, verbose_name='사용자이름'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='휴대폰번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_pw',
            field=models.CharField(max_length=15, verbose_name='비밀번호'),
        ),
        migrations.AlterModelTable(
            name='member',
            table='member_member',
        ),
    ]
