# Generated by Django 3.2.4 on 2021-07-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendHistroy',
            new_name='Attendences',
        ),
    ]
