# Generated by Django 3.2.4 on 2021-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAllContentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seenum', models.IntegerField(null=True)),
                ('like', models.IntegerField(null=True)),
                ('board_kind', models.CharField(max_length=20)),
            ],
        ),
    ]
