# Generated by Django 3.2.4 on 2021-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardallcontentlist',
            name='like',
            field=models.ManyToManyField(default=0, related_name='likes', to='member.Member'),
        ),
    ]
