# Generated by Django 3.2.4 on 2021-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_alter_boardallcontentlist_seenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardallcontentlist',
            name='seenum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
