# Generated by Django 3.2.4 on 2021-07-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210704_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardallcontentlist',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boardallcontentlist',
            name='seenum',
            field=models.IntegerField(null=True),
        ),
    ]
