# Generated by Django 3.2.4 on 2021-07-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20210704_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_board_kind', models.CharField(max_length=20)),
                ('comment_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boardapp.boardallcontentlist')),
            ],
        ),
    ]
