# Generated by Django 3.2.4 on 2021-07-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_board_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_comment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boardapp.boardallcontentlist'),
        ),
        migrations.AlterField(
            model_name='board_comment',
            name='comment_content',
            field=models.TextField(null=True),
        ),
    ]
