# Generated by Django 3.2.4 on 2021-07-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_auto_20210704_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_comment',
            name='comment_board_kind',
        ),
        migrations.AlterField(
            model_name='board_comment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='boardapp.boardallcontentlist'),
        ),
    ]
