# Generated by Django 3.2.4 on 2021-07-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_tel',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
