# Generated by Django 3.2.5 on 2021-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210701_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
