# Generated by Django 3.2.4 on 2021-07-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210704_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_price',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='rest',
            name='rest_tel',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_name',
            field=models.CharField(max_length=50),
        ),
    ]
