# Generated by Django 3.2.4 on 2021-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rest_rest_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_price',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
