# Generated by Django 3.2.4 on 2021-07-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rest_rest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='starscore',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
