# Generated by Django 3.2.4 on 2021-07-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210705_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='rest_starscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_rmd',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
