# Generated by Django 3.2.4 on 2021-07-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rest_starscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest',
            old_name='starscore',
            new_name='rest_starscore',
        ),
    ]
