# Generated by Django 3.2.4 on 2021-07-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_starscore_rest_rest_starscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='rest_img1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_img2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_img3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rest',
            name='rest_img4',
            field=models.CharField(max_length=200),
        ),
    ]
