# Generated by Django 3.2.4 on 2021-07-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210705_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='rest_img3',
        ),
        migrations.RemoveField(
            model_name='rest',
            name='rest_img4',
        ),
    ]
